### ISSUE TITLE
Gazebo crashes when importing a new image

### ISSUE THREAD

**Issue by zmk5** [MatthewVerbryke/gazebo_terrain#1]
Hi @MatthewVerbryke,

I recently tried testing out your script with ROS Kinetic and Gazebo 7.0 and have run into some issues after importing [this image](https://i.stack.imgur.com/5koQD.png) after using your tool. I've tried lowering the resolution and such but it keeps crashing as well. Is the tool only able to work in Gazebo 7.9 like you have wrote?

**Comment by MatthewVerbryke** [comment]
Hello,

In short, yes you will need to upgrade to 7.9. I have not tried it myself, but based on issues others have had (see [here](http://answers.gazebosim.org/question/17984/heightmap-insertion-unsuccessful-with-gazebo-7/)), I believe terrain insertion doesn't work below Gazebo 7.9. 

Hope this helps.

**Comment by zmk5** [comment]
Yes! That definitely helps. Thank you for your input!
